# Generated by Django 2.1.1 on 2020-09-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200912_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='curp',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='telefono',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
